### PR TITLE
Add Debian Buster support

### PR DESCRIPTION
**Pull request by MaxVigne**
* Use OpenJDK 11 as the default on Debian Buster
* Update molecule tests to test Debian Buster

### CODE REVIEW

**Comment by captainju** [comment]
I think the README has to be updated with the default openjdk 11 on buster.

As a side bonus, I can't see anyone using the `keep_oracle_jdk` variable, maybe we can remove it and simplify the playbook ? (or we keep this for another issue)

**Comment by MaxVigne** [comment]
@captainju Done :+1:

**Review by captainju — APPROVED** [review]

**Comment by captainju** [comment]
> @captainju Done +1

:+1:

**Review by wsourdin — APPROVED** [review]

**Comment by MaxVigne** [comment]
@captainju @wsourdin I'll let you merge the PR (I lost write rights to the repository).

**Pull request merged**
